name: Publish mod on Modrinth

on: [ push, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: validate gradle wrapper
        uses: https://github.com/gradle/wrapper-validation-action@v1
      - name: setup jdk
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'oracle'
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: |
          chmod +x ./gradlew
          touch local.properties
      - name: Generate data
        run: ./gradlew runDatagen
      - name: Publish Modrinth
        run: ./gradlew modrinth
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}